name: Build PosQuantum Desktop - FINAL CORRECTED

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'
  QT_QPA_PLATFORM: 'offscreen'

jobs:
  validate-code:
    name: Validate Code Structure
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Validate main.py exists
      run: |
        if [ ! -f main.py ]; then
          echo "❌ main.py not found"
          exit 1
        fi
        echo "✅ main.py found ($(wc -l < main.py) lines)"
        
    - name: Validate Python syntax
      run: |
        python3 -m py_compile main.py
        echo "✅ Python syntax valid"

  test-imports:
    name: Test Imports
    runs-on: ubuntu-22.04
    needs: validate-code
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxcb-xinerama0 libxcb-cursor0 libxkbcommon-x11-0
        
    - name: Create requirements.txt
      run: |
        cat > requirements.txt << EOF
        PyQt6==6.6.1
        cryptography==41.0.7
        requests==2.31.0
        numpy==1.24.3
        scikit-learn==1.3.0
        pyinstaller==6.3.0
        psutil==5.9.5
        pycryptodome==3.19.0
        EOF
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create required directories
      run: |
        mkdir -p posquantum_modules/core
        touch posquantum_modules/__init__.py
        touch posquantum_modules/core/__init__.py
        
    - name: Test import with comprehensive diagnostics
      run: |
        echo "=== COMPREHENSIVE DIAGNOSTIC START ==="
        echo "Timestamp: $(date)"
        echo "Working Directory: $(pwd)"
        echo "User: $(whoami)"
        echo "Python Version: $(python3 --version)"
        echo "Python Path: $(which python3)"
        
        echo "=== ENVIRONMENT VARIABLES ==="
        env | grep -E "(PYTHON|PATH|QT)" | sort
        
        echo "=== DIRECTORY CONTENTS ==="
        ls -la
        
        echo "=== MAIN.PY FILE INFO ==="
        if [ -f "main.py" ]; then
          echo "File exists: YES"
          echo "File size: $(stat -c%s main.py) bytes"
          echo "File permissions: $(stat -c%A main.py)"
          echo "File encoding: $(file -b --mime-encoding main.py)"
          echo "First 10 lines:"
          head -10 main.py
          echo "Last 5 lines:"
          tail -5 main.py
        else
          echo "File exists: NO"
          echo "Files in directory:"
          find . -name "*.py" -type f
        fi
        
        echo "=== PYTHON SYNTAX CHECK ==="
        python3 -m py_compile main.py && echo "✅ Syntax OK" || echo "❌ Syntax ERROR"
        
        echo "=== PYTHON IMPORT PATH ==="
        python3 -c "import sys; print('\\n'.join(sys.path))"
        
        echo "=== DEPENDENCIES CHECK ==="
        python3 -c "import pkg_resources; print('\\n'.join([str(d) for d in pkg_resources.working_set]))" | grep -i crypto
        
        echo "=== SETTING QT ENVIRONMENT ==="
        export QT_QPA_PLATFORM=offscreen
        echo "QT_QPA_PLATFORM set to: $QT_QPA_PLATFORM"
        
        echo "=== BASIC PYTHON TEST ==="
        python3 -c "print('✅ Basic Python execution works')"
        
        echo "=== SIMPLE IMPORT TEST ==="
        python3 -c "import os, sys; print('✅ Basic imports work')"
        
        echo "=== CRYPTO IMPORT TEST ==="
        python3 -c "from Crypto.Cipher import AES; print('✅ PyCryptodome import works')" || echo "❌ PyCryptodome import failed"
        
        echo "=== MAIN IMPORT TEST WITH VERBOSE ==="
        python3 -v -c "import main; print('✅ Main import successful')" 2>&1 | tee import_verbose.log
        
        echo "=== IMPORT LOG ANALYSIS ==="
        if [ -f "import_verbose.log" ]; then
          echo "Log file size: $(stat -c%s import_verbose.log) bytes"
          echo "Errors in log:"
          grep -i "error\|exception\|failed\|traceback" import_verbose.log || echo "No errors found in verbose log"
        fi
        
        echo "=== COMPREHENSIVE DIAGNOSTIC END ==="

  build-executables:
    name: Build Executables
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: test-imports
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxcb-xinerama0 libxcb-cursor0 libxkbcommon-x11-0
        
    - name: Create requirements.txt
      run: |
        cat > requirements.txt << EOF
        PyQt6==6.6.1
        cryptography==41.0.7
        requests==2.31.0
        numpy==1.24.3
        scikit-learn==1.3.0
        pyinstaller==6.3.0
        psutil==5.9.5
        pycryptodome==3.19.0
        EOF
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create required directories
      run: |
        mkdir -p posquantum_modules/core
        touch posquantum_modules/__init__.py
        touch posquantum_modules/core/__init__.py
        
    - name: Test import before build (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        export QT_QPA_PLATFORM=offscreen
        python -c "import main; print('✅ Import test passed')"
        
    - name: Test import before build (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $env:QT_QPA_PLATFORM = "offscreen"
        python -c "import main; print('✅ Import test passed')"
        
    - name: Build executable (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        export QT_QPA_PLATFORM=offscreen
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 2
        pyinstaller --onefile --name=PosQuantumDesktop-Linux \
          --add-data="posquantum_modules:posquantum_modules" \
          --hidden-import=PyQt6.QtCore \
          --hidden-import=PyQt6.QtGui \
          --hidden-import=PyQt6.QtWidgets \
          --hidden-import=cryptography \
          --collect-all=PyQt6 \
          main.py
          
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $env:QT_QPA_PLATFORM = "offscreen"
        pyinstaller --onefile --name=PosQuantumDesktop-Windows `
          --add-data="posquantum_modules;posquantum_modules" `
          --hidden-import=PyQt6.QtCore `
          --hidden-import=PyQt6.QtGui `
          --hidden-import=PyQt6.QtWidgets `
          --hidden-import=cryptography `
          --collect-all=PyQt6 `
          main.py
          
    - name: Verify executable (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        if [ -f dist/PosQuantumDesktop-Linux ]; then
          echo "✅ Linux executable created"
          ls -la dist/PosQuantumDesktop-Linux
        else
          echo "❌ Linux executable not found"
          exit 1
        fi
        
    - name: Verify executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        if (Test-Path dist\PosQuantumDesktop-Windows.exe) {
          Write-Host "✅ Windows executable created"
          Get-ChildItem dist\PosQuantumDesktop-Windows.exe
        } else {
          Write-Host "❌ Windows executable not found"
          exit 1
        }
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: PosQuantumDesktop-${{ matrix.os }}
        path: |
          dist/PosQuantumDesktop-Linux
          dist/PosQuantumDesktop-Windows.exe

  create-release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs: build-executables
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts/
        
    - name: List artifacts
      run: |
        echo "📦 Downloaded artifacts:"
        find ./artifacts/ -type f -exec ls -la {} \;
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: PosQuantum Desktop v${{ github.run_number }}
        body: |
          ## 🚀 PosQuantum Desktop Release v${{ github.run_number }}
          
          ### ✨ Features:
          - 🔐 Post-quantum cryptography implementation
          - 🖥️ Cross-platform desktop application  
          - 🔧 Windows and Linux executables
          - 🛡️ Advanced security features
          
          ### 📥 Downloads:
          - **Windows:** PosQuantumDesktop-Windows.exe
          - **Linux:** PosQuantumDesktop-Linux
          
          ### 🔧 Installation:
          1. Download the appropriate executable for your platform
          2. Run the executable directly (no installation required)
          3. Enjoy post-quantum security! 🛡️
          
          **Built from commit:** ${{ github.sha }}
          **Build date:** ${{ github.run_id }}
        draft: false
        prerelease: false

