name: Build PosQuantum Desktop - Ultra Simple

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6
        pip install cryptography
        pip install pyinstaller
        
    - name: Create executable
      run: |
        python -m PyInstaller --onefile --windowed --name=PosQuantum main.py
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: PosQuantum-Windows
        path: dist/PosQuantum.exe
        
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0 libxkbcommon-x11-0
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6
        pip install cryptography
        pip install pyinstaller
        
    - name: Create executable
      run: |
        python -m PyInstaller --onefile --windowed --name=PosQuantum main.py
        
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: PosQuantum-Linux
        path: dist/PosQuantum
        
  build-macos:
    runs-on: macos-12
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6
        pip install cryptography
        pip install pyinstaller
        
    - name: Create executable
      run: |
        python -m PyInstaller --onefile --windowed --name=PosQuantum main.py
        
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: PosQuantum-macOS
        path: dist/PosQuantum
        
  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v2.0.0-${{ github.run_number }}
        name: "PosQuantum Desktop v2.0.0 Build ${{ github.run_number }}"
        body: |
          PosQuantum Desktop v2.0.0 - Primeiro Software Desktop 100% Pos-Quantico
          
          Funcionalidades:
          - Criptografia Pos-Quantica: ML-KEM-768, ML-DSA-65, SPHINCS+
          - Rede P2P para comunicacao intercomputadores
          - Blockchain QuantumCoin integrado
          - Interface PyQt6 moderna
          - Sistema 100% resistente a computadores quanticos
          
          Downloads:
          - Windows: PosQuantum.exe
          - Linux: PosQuantum
          - macOS: PosQuantum
        files: |
          PosQuantum-Windows/PosQuantum.exe
          PosQuantum-Linux/PosQuantum
          PosQuantum-macOS/PosQuantum
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

