name: Build PosQuantum

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            executable: PosQuantum-3.0.exe
            artifact: PosQuantum-Windows
            separator: ";"
          - os: ubuntu-latest
            platform: linux
            executable: PosQuantum-3.0
            artifact: PosQuantum-Linux
            separator: ":"
          - os: macos-latest
            platform: macos
            executable: PosQuantum-3.0
            artifact: PosQuantum-macOS
            separator: ":"
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Create runtime hooks directory
        run: mkdir -p hooks
        shell: bash

      - name: Create runtime hook file
        run: |
          echo "# -*- coding: utf-8 -*-" > hooks/runtime_hook.py
          echo "import os" >> hooks/runtime_hook.py
          echo "import sys" >> hooks/runtime_hook.py
          echo "" >> hooks/runtime_hook.py
          echo "# Corrigir sys.path para garantir que todos os módulos sejam encontrados" >> hooks/runtime_hook.py
          echo "if hasattr(sys, '_MEIPASS'):" >> hooks/runtime_hook.py
          echo "    # Executando a partir do executável PyInstaller" >> hooks/runtime_hook.py
          echo "    base_dir = sys._MEIPASS" >> hooks/runtime_hook.py
          echo "else:" >> hooks/runtime_hook.py
          echo "    # Executando a partir do script" >> hooks/runtime_hook.py
          echo "    base_dir = os.path.dirname(os.path.abspath(__file__))" >> hooks/runtime_hook.py
          echo "" >> hooks/runtime_hook.py
          echo "# Adicionar diretório base ao path" >> hooks/runtime_hook.py
          echo "if base_dir not in sys.path:" >> hooks/runtime_hook.py
          echo "    sys.path.insert(0, base_dir)" >> hooks/runtime_hook.py
          echo "" >> hooks/runtime_hook.py
          echo "# Adicionar diretórios de módulos ao path" >> hooks/runtime_hook.py
          echo "module_dirs = [" >> hooks/runtime_hook.py
          echo "    os.path.join(base_dir, 'posquantum_modules')," >> hooks/runtime_hook.py
          echo "    os.path.join(base_dir, 'posquantum_modules', 'crypto')," >> hooks/runtime_hook.py
          echo "    os.path.join(base_dir, 'posquantum_modules', 'network')," >> hooks/runtime_hook.py
          echo "    os.path.join(base_dir, 'posquantum_modules', 'compliance')," >> hooks/runtime_hook.py
          echo "    os.path.join(base_dir, 'posquantum_modules', 'core')," >> hooks/runtime_hook.py
          echo "    os.path.join(base_dir, 'posquantum_modules', 'security')," >> hooks/runtime_hook.py
          echo "    os.path.join(base_dir, 'posquantum_modules', 'ui')" >> hooks/runtime_hook.py
          echo "]" >> hooks/runtime_hook.py
          echo "" >> hooks/runtime_hook.py
          echo "for module_dir in module_dirs:" >> hooks/runtime_hook.py
          echo "    if os.path.exists(module_dir) and module_dir not in sys.path:" >> hooks/runtime_hook.py
          echo "        sys.path.insert(0, module_dir)" >> hooks/runtime_hook.py
          echo "" >> hooks/runtime_hook.py
          echo "# Configurar variáveis de ambiente" >> hooks/runtime_hook.py
          echo "os.environ['POSQUANTUM_BASE_DIR'] = base_dir" >> hooks/runtime_hook.py
          echo "" >> hooks/runtime_hook.py
          echo "# Debug" >> hooks/runtime_hook.py
          echo "print('Runtime hook executado com sucesso')" >> hooks/runtime_hook.py
          echo "print(f'sys.path: {sys.path}')" >> hooks/runtime_hook.py
          echo "print(f'Diretório base: {base_dir}')" >> hooks/runtime_hook.py
        shell: bash

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --clean --noconfirm --onefile --name="PosQuantum-3.0" --add-data="assets${{ matrix.separator }}assets" --add-data="posquantum_modules${{ matrix.separator }}posquantum_modules" --hidden-import="PyQt6.QtCore" --hidden-import="PyQt6.QtGui" --hidden-import="PyQt6.QtWidgets" --hidden-import="posquantum_modules.crypto" --hidden-import="posquantum_modules.network" --hidden-import="posquantum_modules.compliance" --hidden-import="posquantum_modules.core" --hidden-import="posquantum_modules.security" --hidden-import="posquantum_modules.ui" --hidden-import="posquantum_modules.crypto.ml_kem" --hidden-import="posquantum_modules.crypto.ml_dsa" --hidden-import="posquantum_modules.crypto.sphincs_plus" --hidden-import="posquantum_modules.crypto.elliptic_curve_pq_hybrid" --hidden-import="posquantum_modules.crypto.hsm_virtual" --hidden-import="posquantum_modules.network.vpn_pq" --hidden-import="posquantum_modules.compliance.certifications" --hidden-import="posquantum_modules.core.blockchain_real_implementation_clean" --hidden-import="posquantum_modules.core.crypto_real_implementation_clean" --hidden-import="posquantum_modules.core.dashboard_real_implementation_clean" --hidden-import="posquantum_modules.core.i18n_system" --runtime-hook="hooks/runtime_hook.py" main.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/${{ matrix.executable }}

      - name: Create Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v3.0-${{ github.run_number }}
          name: PosQuantum v3.0 Build ${{ github.run_number }}
          draft: false
          prerelease: false
          body: |
            PosQuantum v3.0 - Sistema de Segurança Pós-Quântica
            Build automático gerado pelo GitHub Actions.
            
            Plataformas disponíveis:
            - Windows
            - Linux
            - macOS
            
            Todas as funcionalidades implementadas com criptografia pós-quântica em todas as camadas.
          files: |
            dist/${{ matrix.executable }}

