name: Build PosQuantum Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build PosQuantum for Windows
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.POSQUANTUM_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6
          pip install -r requirements.txt
        shell: cmd

      - name: Create runtime hooks directory
        run: mkdir hooks
        shell: cmd

      - name: Create runtime hook file
        run: |
          echo # -*- coding: utf-8 -*- > hooks\runtime_hook.py
          echo import os >> hooks\runtime_hook.py
          echo import sys >> hooks\runtime_hook.py
          echo. >> hooks\runtime_hook.py
          echo # Corrigir sys.path para garantir que todos os módulos sejam encontrados >> hooks\runtime_hook.py
          echo if hasattr(sys, '_MEIPASS'^): >> hooks\runtime_hook.py
          echo     # Executando a partir do executável PyInstaller >> hooks\runtime_hook.py
          echo     base_dir = sys._MEIPASS >> hooks\runtime_hook.py
          echo else: >> hooks\runtime_hook.py
          echo     # Executando a partir do script >> hooks\runtime_hook.py
          echo     base_dir = os.path.dirname(os.path.abspath(__file__^)^) >> hooks\runtime_hook.py
          echo. >> hooks\runtime_hook.py
          echo # Adicionar diretório base ao path >> hooks\runtime_hook.py
          echo if base_dir not in sys.path: >> hooks\runtime_hook.py
          echo     sys.path.insert(0, base_dir^) >> hooks\runtime_hook.py
          echo. >> hooks\runtime_hook.py
          echo # Adicionar diretórios de módulos ao path >> hooks\runtime_hook.py
          echo module_dirs = [ >> hooks\runtime_hook.py
          echo     os.path.join(base_dir, 'posquantum_modules'^), >> hooks\runtime_hook.py
          echo     os.path.join(base_dir, 'posquantum_modules', 'crypto'^), >> hooks\runtime_hook.py
          echo     os.path.join(base_dir, 'posquantum_modules', 'network'^), >> hooks\runtime_hook.py
          echo     os.path.join(base_dir, 'posquantum_modules', 'compliance'^), >> hooks\runtime_hook.py
          echo     os.path.join(base_dir, 'posquantum_modules', 'core'^), >> hooks\runtime_hook.py
          echo     os.path.join(base_dir, 'posquantum_modules', 'security'^), >> hooks\runtime_hook.py
          echo     os.path.join(base_dir, 'posquantum_modules', 'ui'^) >> hooks\runtime_hook.py
          echo ] >> hooks\runtime_hook.py
          echo. >> hooks\runtime_hook.py
          echo for module_dir in module_dirs: >> hooks\runtime_hook.py
          echo     if os.path.exists(module_dir^) and module_dir not in sys.path: >> hooks\runtime_hook.py
          echo         sys.path.insert(0, module_dir^) >> hooks\runtime_hook.py
          echo. >> hooks\runtime_hook.py
          echo # Configurar variáveis de ambiente >> hooks\runtime_hook.py
          echo os.environ['POSQUANTUM_BASE_DIR'] = base_dir >> hooks\runtime_hook.py
          echo. >> hooks\runtime_hook.py
          echo # Debug >> hooks\runtime_hook.py
          echo print('Runtime hook executado com sucesso'^) >> hooks\runtime_hook.py
          echo print(f'sys.path: {sys.path}'^) >> hooks\runtime_hook.py
          echo print(f'Diretório base: {base_dir}'^) >> hooks\runtime_hook.py
        shell: cmd

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --clean --noconfirm --onefile --name="PosQuantum" --add-data="posquantum_modules;posquantum_modules" --hidden-import="PyQt6.QtCore" --hidden-import="PyQt6.QtGui" --hidden-import="PyQt6.QtWidgets" --hidden-import="posquantum_modules.crypto" --hidden-import="posquantum_modules.network" --hidden-import="posquantum_modules.compliance" --hidden-import="posquantum_modules.core" --hidden-import="posquantum_modules.security" --hidden-import="posquantum_modules.ui" --hidden-import="posquantum_modules.crypto.ml_kem" --hidden-import="posquantum_modules.crypto.ml_dsa" --hidden-import="posquantum_modules.crypto.sphincs_plus" --hidden-import="posquantum_modules.crypto.elliptic_curve_pq_hybrid" --hidden-import="posquantum_modules.crypto.hsm_virtual" --hidden-import="posquantum_modules.network.vpn_pq" --hidden-import="posquantum_modules.compliance.certifications" --runtime-hook="hooks/runtime_hook.py" main.py
        shell: cmd

      - name: Verify executable
        run: |
          dir dist
          if exist "dist\PosQuantum.exe" (
            echo Executável PosQuantum.exe criado com sucesso!
            echo Tamanho do arquivo:
            dir "dist\PosQuantum.exe"
          ) else (
            echo ERRO: Executável não foi criado!
            exit 1
          )
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PosQuantum-Windows
          path: dist/PosQuantum.exe

      - name: Create Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.POSQUANTUM_TOKEN }}
          tag_name: v3.0-${{ github.run_number }}
          name: PosQuantum v3.0 Build ${{ github.run_number }}
          draft: false
          prerelease: false
          body: |
            PosQuantum v3.0 - Sistema de Segurança Pós-Quântica para Windows
            Build automático gerado pelo GitHub Actions.
            
            Funcionalidades incluídas:
            ✅ 16 abas/módulos completos
            ✅ Mais de 70 funcionalidades
            ✅ Criptografia pós-quântica em todas as camadas
            ✅ ML-KEM, ML-DSA, SPHINCS+ (NIST)
            ✅ Curva elíptica híbrida
            ✅ Conformidade com certificações (FIPS 140-3, Common Criteria EAL4, ISO 27001, SOC 2 Type II)
            
            Executável: PosQuantum.exe
            Plataforma: Windows (x64)
            Tamanho: ~25-35MB
          files: |
            dist/PosQuantum.exe

